  var language_es = {
      errorTitle : 'Ha fallado el env&iacute;o del formulario!',
      requiredFields : 'Usted no ha completado todos los campos requeridos',
      andSpaces : ' y espacios',      
      badTime : 'Usted ha proporcionado una hora incorrecta',
      badEmail : 'Usted ha proporcionado un e-mail incorrecto',
      badTelephone : 'Usted ha proporcionado un n&uacute;mero telef&oacute;nico incorrecto',
      badSecurityAnswer : 'Usted ha proporcionado una respuesta inv&aacute;lida a la pregunta de seguridad',
      badDate : 'Usted ha proporcionado una fecha inv&aacute;lida',
      lengthBadStart : 'Usted debe dar una respuesta entre ',
      lengthBadEnd : ' caracteres',
      lengthTooLongStart : 'Usted ha proporcionado una respuesta mayor a ',
      lengthTooShortStart : 'Usted ha proporcionado una respuesta menor a ',
      notConfirmed : 'Los valores no han sido confirmados',
      badDomain : 'Dominio incorrecto',
      badUrl : 'Su respuesta es una URL inv&aacute;lida',
      badCustomVal : 'Usted ha proporcionado una respuesta inv&aacute;lida',
      badInt : 'Usted ha proporcionado un n&uacute;mero incorrecto',
      badSecurityNumber : 'Su n&uacute;mero de seguro social es incorrecto',
      badUKVatAnswer : 'N&uacute;mero UK VAT incorrecto',
      badStrength : 'El password no satisface los requisitos m&iacute;nimos de seguridad',
      badNumberOfSelectedOptionsStart : 'Usted debe seleccionar al menos ',
      badNumberOfSelectedOptionsEnd : ' respuestas',
      badAlphaNumeric : 'La respuesta debe contener solo caracteres alfanum&eacute;ricos ',
      badAlphaNumericExtra: ' inclu&iacute;dos ',
      badAlphabetic : 'La respuesta debe contener solo caracteres alfab&eacute;ticos ',
      badAlphabeticExtra: ' inclu&iacute;dos ',
      wrongFileSize : 'El archivo que trata de subir es demasado grande',
      wrongFileType : 'El archivo que trata de subir es de un tipo inv&aacute;lido',
      groupCheckedRangeStart : 'Por favor, selecciones entre ',
      groupCheckedTooFewStart : 'Por favor, seleccione al menos ',
      groupCheckedTooManyStart : 'Por favor, seleccione un m&aacute;ximo de ',
      groupCheckedEnd : ' &iacute;tem(s)'
    };